/* =========================================================
   GAMUT - AI Import Package
   Packages a palette + pairing into a ZIP any AI coding tool
   (Claude Code, Codex, Cursor, Gemini CLI, Windsurf, or similar)
   can attach and hand to a Figma-capable agent: the raw tokens,
   a human-readable brand book, and a generated import prompt.

   Pure functions only - no DOM, no network, no LLM call. And,
   critically, fully deterministic: the same (palette, pair) must
   produce the same bytes every time, or a designer re-exporting
   an unchanged palette gets a diff with nothing in it to explain.
   That means no Date.now(), no `new Date()`, no Math.random(),
   no locale-dependent formatting anywhere in this file - including
   inside the hand-rolled ZIP container below, which is why its
   timestamp field is a fixed constant rather than "now".
   ========================================================= */

"use strict";

/* ---------- Law titles ----------
   Copied verbatim from the <details> summaries in index.html's
   Method section - the ten laws are documentation, not something
   this file gets to paraphrase. */
const AIPACK_LAWS = [
    { n: 1, title: "Pick a dark anchor before you pick a bright" },
    { n: 2, title: "Saturate the brand color, mute the accent" },
    { n: 3, title: "Test at 5% of the screen, not 50%" },
    { n: 4, title: "Design the dark mode at the same time as the light" },
    { n: 5, title: "One bold color is a brand. Three is a circus" },
    { n: 6, title: "Use color for hierarchy, not decoration" },
    { n: 7, title: "Borrow a palette from a category you are not in" },
    { n: 8, title: "Build the ramp, not the swatch" },
    { n: 9, title: "Contrast is a floor, not a vibe" },
    { n: 10, title: "Check the culture map before crossing borders" }
];

function aipackEngine(engine) {
    return engine || (typeof window !== "undefined" ? window.Engine : undefined);
}

/* The archetype's own label doubles as this package's title context -
   it is the same "signal" ARCHETYPES already carries, just read for
   its label instead of its hue ranges. Fixer palettes have no category
   at all, hence no false provenance. */
function categoryLabel(p, E) {
    if (p.category && E.ARCHETYPES && E.ARCHETYPES[p.category]) return E.ARCHETYPES[p.category].label;
    return "Custom system";
}

function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1); }

/* ---------- README.md ---------- */

function buildReadme() {
    return `# Gamut AI Import Package

This ZIP is a complete, ready-to-import brand system generated by Gamut. Attach it directly to Claude Code, Codex, Cursor, Gemini CLI, Windsurf, or any other AI coding or design tool that can create or edit Figma files, and it has everything needed to build out a full design system from the values inside.

## What's in here

- **brand-system.json** - package metadata: provenance (which seed, or that this came from the Fixer), the palette's own signal line, the ten laws of color, and the contrast report.
- **tokens.json** - the full design system token set: color roles, both deployments, component states, spacing, radius, elevation, and typography. Schema \`gamut.tokens.v1\`.
- **brand-book.md** - human-readable documentation of the whole system: the palette, the 60-30-10 rule applied, both deployments, the contrast report, typography, and the full token tables.
- **figma-import.md** - a ready-to-paste prompt for an AI agent, generated from this exact data rather than written by hand. Point your tool at it alongside the attached files.

## How to use it

Attach this ZIP (or its unzipped contents) to your AI tool of choice, then paste the contents of \`figma-import.md\` as your instruction. The agent should build variable collections and a starter component library directly from \`tokens.json\`, cross-checking against \`brand-system.json\` and \`brand-book.md\`.

## Provenance

Everything in this package was generated offline by Gamut's own color and token engine. No AI model produced or touched any of these values. Treat every number, hex code, and name here as canonical - the source of truth for whatever gets built from it, not a draft to be reinterpreted.
`;
}

/* ---------- brand-system.json ---------- */

function buildBrandSystemJson(p, E) {
    const seed = typeof p.seed === "number" ? p.seed : null;
    const obj = {
        schema: "gamut.ai-package.v1",
        product: "Gamut",
        source: {
            seed,
            category: p.category || null,
            recipeKey: p.recipeKey || "custom",
            fromFixer: seed === null
        },
        description: p.signal || "",
        modes: Object.keys(p.deployments),
        laws: AIPACK_LAWS,
        contrast: p.contrasts.map(c => ({
            pair: c.pair,
            ratio: +c.ratio.toFixed(2),
            grade: E.contrastGrade(c.ratio)
        }))
    };
    return JSON.stringify(obj, null, 2);
}

/* ---------- tokens.json ----------
   Engine's own canonical payload, unchanged except for the one
   field that would break determinism. */
function buildTokensJson(p, pair, E) {
    const obj = JSON.parse(E.exportTokensJson(p, pair));
    delete obj.generatedAt;
    return JSON.stringify(obj, null, 2);
}

/* ---------- brand-book.md ---------- */

function buildBrandBook(p, pair, E) {
    const tokens = JSON.parse(E.exportTokensJson(p, pair));
    delete tokens.generatedAt;

    const title = categoryLabel(p, E);
    const provenance = typeof p.seed === "number" ? `Seed: ${p.seed}` : "Rebuilt by the Fixer";

    const lines = [];
    lines.push(`# ${title}`);
    lines.push("");
    lines.push(provenance);
    lines.push("");

    lines.push("## Palette");
    lines.push("");
    lines.push("| Role | Name | Hex | RGB | CMYK | Job |");
    lines.push("|---|---|---|---|---|---|");
    p.swatches.forEach(s => {
        lines.push(`| ${s.role} | ${s.name} | ${s.hex} | ${s.rgb.r} ${s.rgb.g} ${s.rgb.b} | ${s.cmyk.c} ${s.cmyk.m} ${s.cmyk.y} ${s.cmyk.k} | ${s.job} |`);
    });
    const printNotes = p.swatches.filter(s => s.print && s.print.risk !== "none");
    if (printNotes.length) {
        lines.push("");
        printNotes.forEach(s => {
            lines.push(`- Print risk: **${s.role}** (${s.hex}) shifts ${s.print.risk} on press; press-safer alternate ${s.print.safeHex}.`);
        });
    }
    lines.push("");

    lines.push("## The 60-30-10 rule");
    lines.push("");
    lines.push("Dominant 60 - the canvas, not the brand. Brand 30 - the color people remember. Accent 10 - the pop, used sparingly. Ink = text - the dark anchor grounding everything else; it carries no share of the layout because its job is reading the words, not filling space.");
    lines.push("");

    lines.push("## Deployments");
    Object.keys(p.deployments).forEach(mode => {
        const dep = p.deployments[mode];
        lines.push("");
        lines.push(`### ${capitalize(mode)}`);
        lines.push("");
        lines.push("| Property | Hex |");
        lines.push("|---|---|");
        Object.keys(dep).forEach(key => {
            lines.push(`| ${key} | ${dep[key]} |`);
        });
    });
    lines.push("");

    lines.push("## Contrast report");
    lines.push("");
    lines.push("| Pair | Ratio | Grade |");
    lines.push("|---|---|---|");
    p.contrasts.forEach(c => {
        lines.push(`| ${c.pair} | ${c.ratio.toFixed(2)} | ${E.contrastGrade(c.ratio)} |`);
    });
    lines.push("");

    if (pair) {
        lines.push("## Typography");
        lines.push("");
        lines.push(`Display: ${pair.display} (weight ${pair.displayWeight})`);
        lines.push("");
        lines.push(`Body: ${pair.body} (weight ${pair.bodyWeight})`);
        if (pair.mono) {
            lines.push("");
            lines.push(`Mono: ${pair.mono}`);
        }
        lines.push("");
        lines.push(pair.why);
        lines.push("");
    }

    lines.push("## Spacing");
    lines.push("");
    lines.push("| Step | Value |");
    lines.push("|---|---|");
    Object.keys(tokens.spacing).forEach(name => {
        lines.push(`| ${name} | ${tokens.spacing[name]} |`);
    });
    lines.push("");

    lines.push("## Radius");
    lines.push("");
    lines.push("| Step | Value |");
    lines.push("|---|---|");
    Object.keys(tokens.radius).forEach(name => {
        lines.push(`| ${name} | ${tokens.radius[name]} |`);
    });
    lines.push("");

    lines.push("## Elevation");
    lines.push("");
    const hasSurface = tokens.elevationSurface && Object.keys(tokens.elevationSurface).length > 0;
    lines.push(hasSurface ? "| Step | Shadow | Surface |" : "| Step | Shadow |");
    lines.push(hasSurface ? "|---|---|---|" : "|---|---|");
    Object.keys(tokens.elevation).forEach(name => {
        if (hasSurface) {
            lines.push(`| ${name} | ${tokens.elevation[name]} | ${tokens.elevationSurface[name] || ""} |`);
        } else {
            lines.push(`| ${name} | ${tokens.elevation[name]} |`);
        }
    });
    lines.push("");

    lines.push("## Component states");
    lines.push("");
    lines.push("| Role | State | Value |");
    lines.push("|---|---|---|");
    Object.keys(tokens.color.states).forEach(role => {
        const states = tokens.color.states[role];
        Object.keys(states).forEach(state => {
            lines.push(`| ${role} | ${state} | ${states[state]} |`);
        });
    });
    lines.push("");

    return lines.join("\n");
}

/* ---------- figma-import.md ----------
   Generated from the token data, not a static template: every
   count and bullet below is read off the actual tokens object, so
   a future token group (the Motion line is written to trigger the
   moment `tokens.motion` exists) appears here with no code change. */
function buildFigmaImport(p, pair, E) {
    const tokens = JSON.parse(E.exportTokensJson(p, pair));
    delete tokens.generatedAt;

    const roleCount = Object.keys(tokens.color.roles).length;
    const stateCount = Object.keys(tokens.color.states)
        .reduce((sum, role) => sum + Object.keys(tokens.color.states[role]).length, 0);
    const deploymentCount = Object.keys(tokens.color.deployments)
        .reduce((sum, mode) => sum + Object.keys(tokens.color.deployments[mode]).length, 0);
    const colorTotal = roleCount + stateCount + deploymentCount;

    const lines = [];
    lines.push("Create a professional Figma design system from the attached files (`tokens.json`, `brand-system.json`, `brand-book.md`).");
    lines.push("");
    lines.push("Create these Variable Collections:");
    lines.push(`- Colors — ${colorTotal} values (${roleCount} roles, ${stateCount} state variants, ${deploymentCount} deployment values)`);
    if (tokens.typography) lines.push("- Typography");
    lines.push(`- Spacing — ${Object.keys(tokens.spacing).length} steps`);
    lines.push(`- Radius — ${Object.keys(tokens.radius).length} steps`);
    lines.push(`- Shadows — ${Object.keys(tokens.elevation).length} steps`);
    /* Generic key check, not a hardcoded "if motion exists in this
       version of the Engine" - the day tokens.json grows a `motion`
       group this line starts appearing with zero changes here. */
    if (Object.prototype.hasOwnProperty.call(tokens, "motion") && tokens.motion) {
        lines.push(`- Motion — ${Object.keys(tokens.motion).length} steps`);
    }
    lines.push("");
    lines.push("Create these modes on the Colors collection:");
    Object.keys(p.deployments).forEach(mode => lines.push(`- ${capitalize(mode)}`));
    lines.push("");
    lines.push("Preserve all token names and values exactly.");
    lines.push("Generate a starter component library — Buttons, Inputs, Cards, Navigation, Form Fields, Badges, and Modals — using the created variables only.");
    lines.push("Do not invent new values.");
    lines.push("If conflicts exist, prefer the supplied tokens.");
    lines.push("");
    lines.push("Key values:");
    p.swatches.forEach(s => lines.push(`- ${s.role} (${s.name}): ${s.hex}`));

    return lines.join("\n") + "\n";
}

/* ---------- buildFiles ---------- */

function buildFiles(p, pair, engine) {
    const E = aipackEngine(engine);
    return [
        { name: "README.md", content: buildReadme() },
        { name: "brand-system.json", content: buildBrandSystemJson(p, E) },
        { name: "tokens.json", content: buildTokensJson(p, pair, E) },
        { name: "brand-book.md", content: buildBrandBook(p, pair, E) },
        { name: "figma-import.md", content: buildFigmaImport(p, pair, E) }
    ];
}

/* ---------- ZIP container (STORE, hand-rolled, no library) ----------
   CRC-32: standard reflected polynomial, table-based. */
function aipackCrcTable() {
    const table = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) {
            c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
        }
        table[n] = c >>> 0;
    }
    return table;
}
const AIPACK_CRC_TABLE = aipackCrcTable();

function aipackCrc32(bytes) {
    let crc = 0xFFFFFFFF;
    for (let i = 0; i < bytes.length; i++) {
        crc = AIPACK_CRC_TABLE[(crc ^ bytes[i]) & 0xFF] ^ (crc >>> 8);
    }
    return (crc ^ 0xFFFFFFFF) >>> 0;
}

/* Fixed DOS date, 2026-01-01: ((year-1980)<<9)|(month<<5)|day. Every
   entry gets the same stamp so two exports of the same palette are
   byte-identical - the whole point of a ZIP a designer might diff
   or re-download without expecting noise. */
const AIPACK_DOS_TIME = 0;
const AIPACK_DOS_DATE = ((2026 - 1980) << 9) | (1 << 5) | 1;

function buildZip(p, pair, engine) {
    const files = buildFiles(p, pair, aipackEngine(engine));
    const encoder = new TextEncoder();

    const localParts = [];
    const centralParts = [];
    let offset = 0;

    files.forEach(f => {
        const nameBytes = encoder.encode(f.name);
        const dataBytes = encoder.encode(f.content);
        const crc = aipackCrc32(dataBytes);
        const size = dataBytes.length;

        const localHeader = new Uint8Array(30);
        const lv = new DataView(localHeader.buffer);
        lv.setUint32(0, 0x04034b50, true);  // local file header signature
        lv.setUint16(4, 20, true);          // version needed to extract
        lv.setUint16(6, 0, true);           // general purpose bit flag
        lv.setUint16(8, 0, true);           // compression method: 0 = store
        lv.setUint16(10, AIPACK_DOS_TIME, true);
        lv.setUint16(12, AIPACK_DOS_DATE, true);
        lv.setUint32(14, crc, true);
        lv.setUint32(18, size, true);       // compressed size (== size, store)
        lv.setUint32(22, size, true);       // uncompressed size
        lv.setUint16(26, nameBytes.length, true);
        lv.setUint16(28, 0, true);          // extra field length

        localParts.push(localHeader, nameBytes, dataBytes);

        const centralHeader = new Uint8Array(46);
        const cv = new DataView(centralHeader.buffer);
        cv.setUint32(0, 0x02014b50, true);  // central directory signature
        cv.setUint16(4, 20, true);          // version made by
        cv.setUint16(6, 20, true);          // version needed to extract
        cv.setUint16(8, 0, true);           // general purpose bit flag
        cv.setUint16(10, 0, true);          // compression method
        cv.setUint16(12, AIPACK_DOS_TIME, true);
        cv.setUint16(14, AIPACK_DOS_DATE, true);
        cv.setUint32(16, crc, true);
        cv.setUint32(20, size, true);
        cv.setUint32(24, size, true);
        cv.setUint16(28, nameBytes.length, true);
        cv.setUint16(30, 0, true);          // extra field length
        cv.setUint16(32, 0, true);          // file comment length
        cv.setUint16(34, 0, true);          // disk number start
        cv.setUint16(36, 0, true);          // internal file attributes
        cv.setUint32(38, 0, true);          // external file attributes
        cv.setUint32(42, offset, true);     // relative offset of local header

        centralParts.push(centralHeader, nameBytes);

        offset += localHeader.length + nameBytes.length + dataBytes.length;
    });

    const centralDirOffset = offset;
    const centralDirSize = centralParts.reduce((sum, part) => sum + part.length, 0);

    const eocd = new Uint8Array(22);
    const ev = new DataView(eocd.buffer);
    ev.setUint32(0, 0x06054b50, true);      // end of central directory signature
    ev.setUint16(4, 0, true);               // number of this disk
    ev.setUint16(6, 0, true);               // disk with start of central directory
    ev.setUint16(8, files.length, true);    // entries on this disk
    ev.setUint16(10, files.length, true);   // total entries
    ev.setUint32(12, centralDirSize, true);
    ev.setUint32(16, centralDirOffset, true);
    ev.setUint16(20, 0, true);              // comment length

    const allParts = localParts.concat(centralParts, [eocd]);
    const total = allParts.reduce((sum, part) => sum + part.length, 0);
    const out = new Uint8Array(total);
    let pos = 0;
    allParts.forEach(part => { out.set(part, pos); pos += part.length; });
    return out;
}

if (typeof window !== "undefined") window.AiPack = { buildFiles, buildZip };
if (typeof module !== "undefined") module.exports = { buildFiles, buildZip };
