name = "gamut-api"
main = "src/index.js"
compatibility_date = "2024-03-20"

[[kv_namespaces]]
binding = "LICENSES"
id = "0422142fb39e4029b8b885d7aa2de099"

[[kv_namespaces]]
binding = "RATELIMIT"
id = "5cc1f57e249148daa0b2abb0ea16dfbd"
