import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LEGAL_DIR = path.join(__dirname, '../legal');

const template = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TITLE}} - Gamut</title>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com;">
    <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%23D4FF00'/%3E%3Ctext x='16' y='23' font-family='Arial Black,sans-serif' font-size='20' font-weight='900' text-anchor='middle' fill='%23141414'%3EG%3C/text%3E%3C/svg%3E">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,600..800&family=Hanken+Grotesk:wght@400;500;600&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
    <nav class="site-nav">
        <a href="../index.html" class="logo wordmark" aria-label="Gamut, home"><span class="wm-text">Gamut</span><span class="logo-dot wm-dot" aria-hidden="true">.</span></a>
        <div class="nav-links" id="nav-links">
            <a href="../index.html#assistant">Assistant</a>
            <a href="../index.html#engine">Engine</a>
            <a href="../index.html#fixer">Fixer</a>
            <a href="../index.html#type">Type</a>
            <a href="../index.html#system">System</a>
            <a href="../index.html#method">Method</a>
            <a href="../index.html#pricing">Pricing</a>
        </div>
    </nav>

    <main id="main-content" tabindex="-1">
        <section class="section">
            <div class="section-head">
                <h2>{{TITLE}}</h2>
            </div>
            <div class="prose" style="max-width: 65ch; margin: 0 auto; line-height: 1.6; font-family: var(--font-body); color: var(--ink);">
                {{CONTENT}}
            </div>
        </section>
    </main>

    <footer class="site-footer" style="margin-top: 4rem;">
        <div class="footer-inner">
            <a href="../index.html" class="footer-mark" aria-label="Gamut, back to top">Gamut.</a>
            <div class="footer-meta">
                <p>Built on The Brand Color Bible. Color is the fastest signal a brand sends.</p>
                <p class="mono footer-handle">
                    <a href="terms.html" style="color: inherit; text-decoration: underline; margin-right: 1rem;">Terms</a>
                    <a href="privacy.html" style="color: inherit; text-decoration: underline; margin-right: 1rem;">Privacy</a>
                    <a href="refunds.html" style="color: inherit; text-decoration: underline; margin-right: 1rem;">Refunds</a>
                    <a href="contact.html" style="color: inherit; text-decoration: underline;">Contact</a>
                </p>
            </div>
        </div>
    </footer>
</body>
</html>`;

const pages = {
    'terms.html': {
        title: 'Terms of Service',
        content: `
            <p>Welcome to Gamut.</p>
            <h3>1. License and Usage</h3>
            <p>Your license grants you access to the features of the tier you purchased. All palettes, systems, and exports generated by Gamut are yours to use in personal, client, or commercial work without restriction.</p>
            <h3>2. Account and Activation</h3>
            <p>Your license code is a bearer token. Keep it private. You may activate it on your own devices.</p>
            <h3>3. Liability</h3>
            <p>Gamut is provided "as is". We are not liable for design outcomes, client rejections, or print errors resulting from the use of our generated colors or values.</p>
            <h3>4. Business Details</h3>
            <p><!-- OWNER: fill business name --> operates this service.</p>
            <p>Address: <!-- OWNER: fill business address --></p>
        `
    },
    'privacy.html': {
        title: 'Privacy Policy',
        content: `
            <p>We respect your privacy and process minimal data.</p>
            <h3>1. What We Collect</h3>
            <p>We process payments through Razorpay, which collects your billing details. We store only your email (to send your license) and an internal license ID.</p>
            <h3>2. What We Don't Collect</h3>
            <p>Your palettes, hex codes, agency settings, and uploaded images never leave your browser. They are processed locally and stored in your device's localStorage.</p>
            <h3>3. Cookies and Tracking</h3>
            <p>We do not use tracking cookies, analytics, or third-party ads. We use localStorage strictly for saving your active palettes and license status.</p>
            <h3>4. Contact</h3>
            <p>For privacy inquiries, contact us at <!-- OWNER: fill contact email -->.</p>
            <p>Business Name: <!-- OWNER: fill business name --><br>
            Address: <!-- OWNER: fill business address --></p>
        `
    },
    'refunds.html': {
        title: 'Refund Policy',
        content: `
            <p>We want you to be completely satisfied with Gamut.</p>
            <h3>7-Day Money-Back Guarantee</h3>
            <p>If Gamut doesn't fit your workflow, contact us within 7 days of purchase for a full refund. Your license will be deactivated.</p>
            <h3>Cancellations</h3>
            <p>You can cancel a subscription at any time. You will retain access until the end of your billing period, after which your account will revert to the Free tier. All palettes generated remain yours forever.</p>
            <h3>Requesting a Refund</h3>
            <p>Email <!-- OWNER: fill contact email --> with your license code and purchase email.</p>
        `
    },
    'contact.html': {
        title: 'Contact',
        content: `
            <p>We're here to help.</p>
            <h3>Support</h3>
            <p>For support, billing issues, or technical help: <a href="mailto:hello@gamut.studio">hello@gamut.studio</a></p>
            <h3>Business Information</h3>
            <p>Business Name: <!-- OWNER: fill business name --><br>
            Address: <!-- OWNER: fill business address --></p>
        `
    }
};

for (const [filename, data] of Object.entries(pages)) {
    const html = template.replace(/{{TITLE}}/g, data.title).replace('{{CONTENT}}', data.content);
    fs.writeFileSync(path.join(LEGAL_DIR, filename), html);
    console.log("Created " + filename);
}
